export const PD_INITIAL_ITEM = 'PD_INITIAL_ITEM'

export const CART_INITIAL_CART = 'INITIAL_CART'
export const CART_ADD_TO_CART = 'ADD_TO_CART'
export const CART_UPDATE_CURRENT_ITEM = 'UPDATE_CURRENT_ITEM'
export const CART_REMOVE_ITEM = 'REMOVE_ITEM'
export const CART_SPECIFY_AMOUNT_ITEM = 'SPECIFY_AMOUNT_ITEM'